# Generated by Django 4.1 on 2023-02-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='price_for_a_day',
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('books', 'Books'), ('clothings', 'Clothings'), ('electronics', 'Electronics')], default=3, max_length=200),
        ),
    ]
